# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 917)
        MainWindow.setMaximumSize(881, 917)
        MainWindow.setMinimumSize(881, 917)

        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_imagem = QtWidgets.QFrame(self.centralwidget)
        self.frame_imagem.setGeometry(QtCore.QRect(240, 20, 341, 101))
        self.frame_imagem.setStyleSheet("QFrame {\n"
"    \n"
"    background-image: url(:/img/Images/Kalunga_logo.png);\n"
"    \n"
"    border-radius: 60px;\n"
"    \n"
"    background-position: center;\n"
"\n"
"}\n"
"QFrame:hover {\n"
"    background-image: url(:/img/Images/Kalunga_logo.png);\n"
"    background-position: center;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.frame_imagem.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imagem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imagem.setObjectName("frame_imagem")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 110, 551, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 47, 39, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 46, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 173, 30, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 236, 33, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";")
        self.label_5.setObjectName("label_5")
        self.pushButton_addveiculo = QtWidgets.QPushButton(self.frame)
        self.pushButton_addveiculo.setGeometry(QtCore.QRect(320, 287, 101, 31))
        self.pushButton_addveiculo.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"   color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(255, 21, 21);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"}")
        self.pushButton_addveiculo.setObjectName("pushButton_addveiculo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_nome.setGeometry(QtCore.QRect(90, 40, 441, 21))
        self.lineEdit_nome.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"\n"
"border: 2px solid red;\n"
"border-radius: 10px;")
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_placa = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_placa.setGeometry(QtCore.QRect(90, 100, 441, 21))
        self.lineEdit_placa.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"\n"
"\n"
"border: 2px solid red;\n"
"border-radius: 10px;")
        self.lineEdit_placa.setObjectName("lineEdit_placa")
        self.lineEdit_cpf = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_cpf.setGeometry(QtCore.QRect(90, 167, 441, 21))
        self.lineEdit_cpf.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"\n"
"\n"
"border: 2px solid red;\n"
"border-radius: 10px;")
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.lineEdit_data = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_data.setGeometry(QtCore.QRect(90, 227, 441, 21))
        self.lineEdit_data.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"\n"
"\n"
"\n"
"\n"
"border: 2px solid red;\n"
"border-radius: 10px;")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(160, 287, 31, 31))
        self.label_8.setStyleSheet("background-image: url(:/img/Images/truck.svg);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(210, 287, 101, 31))
        self.comboBox.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(245, 267, 71, 16))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";")
        self.label_6.setObjectName("label_6")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(72, 493, 31, 31))
        self.label_14.setStyleSheet("background-image: url(:/img/Images/crosshair.svg);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(213, 493, 31, 31))
        self.label_15.setStyleSheet("background-image: url(:/img/Images/smile.svg);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(500, 493, 31, 31))
        self.label_16.setStyleSheet("background-image: url(:/img/Images/plus-circle.svg);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(643, 493, 31, 31))
        self.label_17.setStyleSheet("background-image: url(:/img/Images/check-square.svg);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(357, 493, 31, 31))
        self.label_19.setStyleSheet("background-image: url(:/img/Images/slash.svg);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.pushButton_sobre = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sobre.setGeometry(QtCore.QRect(780, 10, 101, 31))
        self.pushButton_sobre.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"   color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(255, 21, 21);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"}")
        self.pushButton_sobre.setObjectName("pushButton_sobre")
        self.pushButton_deletar_id = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deletar_id.setGeometry(QtCore.QRect(220, 850, 101, 31))
        self.pushButton_deletar_id.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"   color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(255, 21, 21);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"}")
        self.pushButton_deletar_id.setObjectName("pushButton_deletar_id")
        self.lineEdit_data_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data_2.setGeometry(QtCore.QRect(340, 850, 61, 31))
        self.lineEdit_data_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"\n"
"\n"
"\n"
"\n"
"border: 2px solid red;\n"
"border-radius: 10px;")
        self.lineEdit_data_2.setObjectName("lineEdit_data_2")
        self.pushButton_procurar_cpf = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_procurar_cpf.setGeometry(QtCore.QRect(430, 850, 101, 31))
        self.pushButton_procurar_cpf.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"   color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(255, 21, 21);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"}")
        self.pushButton_procurar_cpf.setObjectName("pushButton_procurar_cpf")
        self.lineEdit_procurar_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_procurar_cpf.setGeometry(QtCore.QRect(540, 850, 161, 31))
        self.lineEdit_procurar_cpf.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"\n"
"\n"
"\n"
"\n"
"border: 2px solid red;\n"
"border-radius: 10px;")
        self.lineEdit_procurar_cpf.setObjectName("lineEdit_procurar_cpf")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(236, 890, 441, 16))
        self.label_20.setStyleSheet("color: rgb(75, 75, 75);")
        self.label_20.setObjectName("label_20")

        self.tableWidget_logs = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_logs.setGeometry(QtCore.QRect(10, 540, 871, 301))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.tableWidget_logs.setFont(font)
        self.tableWidget_logs.setStyleSheet("font: 81 8pt \"Rockwell Extra Bold\";\n"
"border: 3px solid red;\n"
"\n"
"\n"
"")
        self.tableWidget_logs.setObjectName("tableWidget_logs")
        self.tableWidget_logs.setColumnCount(6)
        self.tableWidget_logs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_logs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_logs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_logs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_logs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_logs.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_logs.setHorizontalHeaderItem(5, item)
        self.tableWidget_logs.horizontalHeader().setDefaultSectionSize(143)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(787, 491, 31, 31))
        self.label_9.setStyleSheet("background-image: url(:/img/Images/truck.svg);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        #self.tableWidget_logs.setColumnHidden(0, True)
        #self.tableWidget_logs.setColumnWidth(0, 0)

        self.pushButton_procurar_cpf.setGeometry(QtCore.QRect(430, 850, 101, 31))
        self.pushButton_procurar_cpf.setStyleSheet("QPushButton {    \n"
                                                   "    background-color: rgb(50, 50, 50);\n"
                                                   "    border: 2px solid rgb(60, 60, 60);\n"
                                                   "    border-radius: 5px;\n"
                                                   "   color: rgb(255, 255, 255);\n"
                                                   "\n"
                                                   "}\n"
                                                   "QPushButton:hover {    \n"
                                                   "    background-color: rgb(255, 21, 21);\n"
                                                   "    border: 2px solid rgb(70, 70, 70);\n"
                                                   "}\n"
                                                   "QPushButton:pressed {    \n"
                                                   "    background-color: rgb(250, 230, 0);\n"
                                                   "    border: 2px solid rgb(255, 165, 24);    \n"
                                                   "}")

        self.pushButton_novobotao = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_novobotao.setGeometry(QtCore.QRect(750, 850, 101, 31))
        self.pushButton_novobotao.setStyleSheet("QPushButton {    \n"
                                                "    background-color: rgb(50, 50, 50);\n"
                                                "    border: 2px solid rgb(60, 60, 60);\n"
                                                "    border-radius: 5px;\n"
                                                "   color: rgb(255, 255, 255);\n"
                                                "\n"
                                                "}\n"
                                                "QPushButton:hover {    \n"
                                                "    background-color: rgb(255, 21, 21);\n"
                                                "    border: 2px solid rgb(70, 70, 70);\n"
                                                "}\n"
                                                "QPushButton:pressed {    \n"
                                                "    background-color: rgb(250, 230, 0);\n"
                                                "    border: 2px solid rgb(255, 165, 24);    \n"
                                                "}")



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "NOME"))
        self.label_2.setText(_translate("MainWindow", "PLACA:"))
        self.label_4.setText(_translate("MainWindow", "CPF:"))
        self.label_5.setText(_translate("MainWindow", "DATA"))
        self.pushButton_addveiculo.setText(_translate("MainWindow", "Adicionar"))
        self.comboBox.setItemText(0, _translate("MainWindow", "CARRETA"))
        self.comboBox.setItemText(1, _translate("MainWindow", "TRUCK"))
        self.comboBox.setItemText(2, _translate("MainWindow", "FIORINO"))
        self.comboBox.setItemText(3, _translate("MainWindow", "HR"))
        self.label_6.setText(_translate("MainWindow", "TIPO"))
        self.pushButton_sobre.setText(_translate("MainWindow", "SOBRE"))
        self.pushButton_deletar_id.setText(_translate("MainWindow", "Deletar ID"))
        self.lineEdit_data_2.setText(_translate("MainWindow", "0"))
        self.pushButton_procurar_cpf.setText(_translate("MainWindow", "Procurar CPF"))
        self.lineEdit_procurar_cpf.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "                                                 By: Felipe Samuel"))
        item = self.tableWidget_logs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_logs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.tableWidget_logs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PLACA"))
        item = self.tableWidget_logs.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.tableWidget_logs.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "DATA"))
        item = self.tableWidget_logs.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TIPO"))
        var2 = "➖" * 2

        var1 = "                                                                                    🔔" + var2

        var3 = "🔔"

        var2 = "➖" * 2 + var3

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", var1 + "Kalunga Check-In - Controle de Acesso - Portaria" + var2))
        self.pushButton_novobotao.setObjectName("pushButton_novobotao")

        self.pushButton_novobotao.setText(_translate("MainWindow", "Resetar dados."))

        #self.pushButton_novobotao.setText("Novo Botão")


import resource
